In [3]:
import numpy as np

> **LIST TO ARRAYS**

In [4]:
li = [1,2,3]
li

[1, 2, 3]

In [5]:
type(li)

list

In [6]:
np.array(li)

array([1, 2, 3])

In [7]:
matrx = [ [1,2,3], [4,5,6], [7,8,9] ]
matrx

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(matrx)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

> **NumPy Built-in Methods**

In [9]:
# array --> 0 - 9
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

> **Zero matrix** and **unity**

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros( (5,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.zeros((50,50))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

> **Linspace**

In [16]:
np.linspace(0,10,40)

array([ 0.        ,  0.25641026,  0.51282051,  0.76923077,  1.02564103,
        1.28205128,  1.53846154,  1.79487179,  2.05128205,  2.30769231,
        2.56410256,  2.82051282,  3.07692308,  3.33333333,  3.58974359,
        3.84615385,  4.1025641 ,  4.35897436,  4.61538462,  4.87179487,
        5.12820513,  5.38461538,  5.64102564,  5.8974359 ,  6.15384615,
        6.41025641,  6.66666667,  6.92307692,  7.17948718,  7.43589744,
        7.69230769,  7.94871795,  8.20512821,  8.46153846,  8.71794872,
        8.97435897,  9.23076923,  9.48717949,  9.74358974, 10.        ])

> **eye of numpy**

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

> **What if we integrate random with numpy** rand() will be always in between 0 to 1

In [19]:
np.random.rand(3)

array([0.60144606, 0.49701633, 0.72325505])

In [20]:
np.random.rand(5,5)

array([[0.51227984, 0.85006724, 0.68975604, 0.02813432, 0.24009888],
       [0.4049947 , 0.6166035 , 0.86127393, 0.64707625, 0.41719317],
       [0.33768022, 0.33011249, 0.16622672, 0.43684084, 0.49186109],
       [0.80126892, 0.10602101, 0.97593894, 0.37931584, 0.94635643],
       [0.55614815, 0.20518746, 0.21343434, 0.67942925, 0.18732247]])

> **randn()**

In [23]:
np.random.randn(5,5)

array([[-1.00046783, -0.92039949, -0.48012247, -1.73969654, -0.35391185],
       [-1.71717885, -1.04926008,  1.10038553,  0.98825568,  0.3147103 ],
       [ 0.62716651,  0.07708679, -0.66820621, -0.40132817,  0.05026189],
       [-1.28314922,  0.05477504, -1.11347193, -1.75437696,  1.13160119],
       [ 0.37789229,  2.053436  ,  0.62253362, -0.06084864,  0.22339416]])

> **randint**

In [24]:
np.random.randint(1,100)

80

In [26]:
np.random.randint(1,100,25)

array([98, 59, 46, 45, 87, 13, 18, 35, 94, 98, 14, 52, 53, 95, 48, 18, 99,
       94, 17, 34, 64, 23, 94, 54,  1])

> **Methods of numpy array**

In [34]:
arr = np.arange(25)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
random_arr = np.random.randint(0,50,10)

In [37]:
random_arr

array([29, 14, 27, 12, 15, 33, 17,  9, 28, 45])

> **Reshape**

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

> **max and min**

In [39]:
random_arr.max()

45

In [40]:
random_arr.min()

9

In [41]:
random_arr.argmax()

9

In [42]:
random_arr.argmin()

7

> **Shape**

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
arr.shape

(25,)

In [46]:
anotherShape = arr.reshape(1,25)

In [47]:
anotherShape.shape

(1, 25)

In [48]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

> **data type**

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
arr.dtype

dtype('int64')