#### NumPy Indexing

In [1]:
import numpy as np

In [6]:
arr = np.arange(23,33)

In [7]:
arr

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [8]:
arr[3]

26

In [14]:
arr[1:5]

array([24, 25, 26, 27])

In [15]:
arr[0:5]

array([23, 24, 25, 26, 27])

In [16]:
arr

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [17]:
arr[0:5] = 555

In [18]:
arr

array([555, 555, 555, 555, 555,  28,  29,  30,  31,  32])

In [19]:
arr = np.arange(0,11)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
slice_arr = arr[0:5]

In [23]:
slice_arr

array([0, 1, 2, 3, 4])

In [26]:
slice_arr[:] = 999 # sob ti element 999 replace hoibo
slice_arr

array([999, 999, 999, 999, 999])

In [27]:
arr

array([999, 999, 999, 999, 999,   5,   6,   7,   8,   9,  10])

In [33]:
copied_arr = arr.copy() # copy korle main array disturb hobena
copied_arr

array([999, 999, 999, 999, 999,   5,   6,   7,   8,   9,  10])

### All about 2D arrays

In [34]:
arr_m = np.array(([45,63,78], [99,103,-98], [0,76,4]))
arr_m

array([[ 45,  63,  78],
       [ 99, 103, -98],
       [  0,  76,   4]])

In [35]:
arr_m[1]

array([ 99, 103, -98])

In [36]:
arr_m[1][1]

103

In [37]:
arr_m[2][1]

76

In [38]:
arr_m[2,1]

76

In [39]:
arr_m

array([[ 45,  63,  78],
       [ 99, 103, -98],
       [  0,  76,   4]])

In [40]:
arr_m[ :2, 1: ] # prothom value hoilo row decide | second value element decide

array([[ 63,  78],
       [103, -98]])

In [42]:
arr_m[ :2, :2 ]

array([[ 45,  63],
       [ 99, 103]])

# Fancy Indexing

In [44]:
# zero matrix

In [45]:
arr_z = np.zeros((10,10))

In [46]:
arr_z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
arr_shape = arr_z.shape

In [49]:
arr_shape

(10, 10)

In [50]:
arr_length = arr_z.shape[1]

In [51]:
arr_length

10

In [54]:
# array bulding
for i in range(arr_length):
    arr_z[i] = i

arr_z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [56]:
arr_z[[2,4,6,8]] # row selection

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [57]:
arr_z[[6,8,2,4]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

## Role of boolean in numpy arrays [MOST IMPORTANT FOR DATA SCIENCE]

In [58]:
arr = np.arange(1,11)

In [59]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

arr > 5

In [61]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr[ arr < 4 ]

array([1, 2, 3])

## OPERATIONS

In [65]:
# arithmetic

In [66]:
import numpy as np
arr = np.arange(0,10)

In [67]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [69]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [70]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [71]:
arr / arr

/tmp/ipykernel_1091/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [72]:
arr + 7

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [73]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [74]:
arr / 5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [75]:
1 / arr

/tmp/ipykernel_1091/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

## Built in functions

In [76]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.sqrt(arr) # sqrt = square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [80]:
np.max(arr)

9

In [81]:
np.min(arr)

0

In [83]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [84]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [85]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [86]:
np.sin(arr) / np.cos(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [87]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [88]:
np.log(arr)

/tmp/ipykernel_1091/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])